<p>&nbsp;</p>
<br clear="all" />
<table width="650" align="center">
<tr>
<td>
<div style="font-family:calibri; font-size:18pt; font-weight:bold; color:#c00000; text-align:center;">Introduction</div>
</td>
</tr>
<tr>
<td style="font-family:Arial; font-size:10pt;">
<div>
  <p>This report is generated by Auto Decision Maker (ADM)  system. ADM is a multi-criteria decision-support system based on the world’s  most popular decision-making methodology: the Analytic Hierarchy Process (AHP).  AHP is a powerful and  comprehensive Multi Criteria Decision Making (MCDM) method developed in 1977 by  Dr Thomas Saaty. It provides groups  and individuals with the ability to incorporate both qualitative and  quantitative factors in the decision making process. The AHP uses a  hierarchical model comprised of a goal, criteria, perhaps several levels of sub  criteria and alternatives for each problem or decision. </p>
  <p>The AHP is a decision support tool which can be used to  solve complex decision problems. It uses a multi-level hierarchical structure  of objectives, criteria, subcriteria, and alternatives.  The pertinent data are derived by using a set of pairwise comparisons. These  comparisons are used to obtain the weights of importance of the decision  criteria, and the relative performance measures of the alternatives in terms of  each individual decision criterion. If the comparisons are not perfectly  consistent, then it provides a mechanism for improving consistency.</p>
  <p>ADM is  a scientific way to make decisions that is practical, user friendly and  correct. It helps you define  the objectives, goals, criteria and alternatives and then organise them into a  hierarchical structure. It allows you to compare and prioritise the relative  importance of the decision variables. ADM then synthesizes your judgments to arrive  at a conclusion and allows you to examine how changing the weighting of your  criteria affects your outcome. The process is outlined below:</p>
</div>
</td>
</tr>
<tr>
<td align="center">
<p><img src="includes/images/process.jpg" /></p>
</td>
</tr>
<tr>
  <td align="center">&nbsp;</td>
</tr>
<tr>
  <td style="font-family:Arial; font-size:10pt;"><p>ADM provides  many results displays designed to give you insights and to make you feel  comfortable making a final choice. The structured visual approach to decision making  simplifies the process, helping you tackle larger, more complex decision  opportunities and select the best choice. </p>
    <p>The report documents the following aspects of your  decision project:</p></td>
</tr>
<tr>
  <td align="center"><img src="includes/images/process2.jpg" /></td>
</tr>
</table>
